import Head from 'next/head'
import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { getCompany } from '../features/thunksHome'

const MyHead = () => {

    const { dataCompany } = useSelector((state) => state.home)
    const dispatch = useDispatch()

    useEffect(() => {
        dispatch(getCompany())

    }, [])
    return (
        <Head>
            {
                dataCompany.map((tag, i) => {
                    return (
                        <React.Fragment key={i}>
                            <title>{tag.name}</title>
                            <link type="image/png" rel="icon" href={tag.imageUrl} />
                        </React.Fragment>

                    )
                })
            }

            <meta name="description" content="Generated by create next app" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
            <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300;700&display=swap" rel="stylesheet" />
        </Head>
    )
}

export default MyHead