
import React from 'react'
import { Contact } from '../../sections/contact'
import Footer from '../../sections/Footer'
import Navbar from '../../sections/navbar'
import Head from 'next/head'


export const LayuotSecondary = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300;700&display=swap" rel="stylesheet" />
            </Head>
            <nav>
                <Navbar />
            </nav>
            <main>

                {children}

            </main>
            <footer>

                <Contact></Contact>

                <Footer />




            </footer>

        </>
    )
}
