import Head from 'next/head'
import { Layout } from '../layouts/homePage/layout'
import Banner from '../sections/banner'
import { Contact } from '../sections/contact'
import { Our } from '../sections/our'
import { LayoutHome } from '../layouts/homePage/layout'
import MyHead from '../components/MyHead'


export default function Home() {
  return (


    <LayoutHome>
      {/*  <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300;700&display=swap" rel="stylesheet" />
      </Head> */}
      <MyHead></MyHead>
      <Banner></Banner>
      <Our></Our>
      <Contact></Contact>
    </LayoutHome>

  )
}

/* Home.getLayout = function getLayout(page) {
  return (
    <LayoutHome>

      {page}

    </LayoutHome>
  )
}
 */